
	
	
	
	
	SuperCollider helpfile: EntTecDMXUSBPro
	

    
    
    

	

EntTecDMXUSBPro
interface to the DMX device EnttecUSBDMXPro
Inherits from:: Object : SerialPort : DMXDevice 



Creation / Class Methods


*new(port)
Create an instance of the EnttecUSBDMXPro.
port
The path to the serial port of the device, e.g. "/dev/ttyUSB0"






Accessing Instance and Class Variables


createFooter


createSendHeader(data_size)




This helpfile was created with the class HelpFile2
 
