
MathLib		Some mathematical extensions to SuperCollider

A diverse library of mathematical functions. See specific helpfiles for more detail:

 * LaTeX
 * Matrix
 * Pboolnet
 * ScatterView and ScatterView3d
 * Trafo
 * MarkovSet and MarkovSetN
 * FuzzySet and FuzzyDictionary
 * ShannonFinger and ShannonMarkovSet
 * extStatistics
 * Bessel
 * Solver
 * Spherical, Cartesian, extPolar, extPoint and extNumber


UNDOCUMENTED THINGS:

 - informationTheory.sc


